export const SWITCH_VIEW = 'SWITCH_VIEW';
export const CLEAR_DATA = 'CLEAR_DATA';
export const SET_AUTH_DATA = 'SET_AUTH_DATA';
export const SET_PERSONAL_DATA = 'SET_PERSONAL_DATA';
export const PROGRESS_INCREASE = 'PROGRESS_INCREASE';
export const PROGRESS_DECREASE = 'PROGRESS_DECREASE';
